### ISSUE TITLE
warn: Login err: {} on Companion RaspberryPi

### ISSUE THREAD

**Issue by danim80** [bitfocus/companion-module-discord-api#10]
**Describe the bug**
Adding Client ID and Client secret (followed the tutorial from the module info)

**To Reproduce**
Steps to reproduce the behaviour:

1. Configure the app with the credentials, save, and check logs

**Expected behaviour**
Should authenticate

**Screenshots**
![image](https://github.com/bitfocus/companion-module-discord-api/assets/7761801/f51a715f-2d16-4255-9f0a-6847a144644d)

**System (please complete the following information):**

- Companion Version 3.0.0 (3.0.0+6000-beta-52f8eec5)

**Additional context**
I even added the actual RPi IP to redirects (not sure is needed)
![image](https://github.com/bitfocus/companion-module-discord-api/assets/7761801/257f7cf5-3675-4dca-a66b-bbee76294ed2)

**Comment by thedist** [comment]
I don't know of any users running Discord on a Raspberry Pi so I haven't been able to test this situation, but just to check, is whatever OS you're running on your Raspberry Pi one that is officially supported by Discord?

**Comment by danim80** [comment]
Discord isn't the main use for the companion PI, mostly is useful for HomeAssistant stuff, to have it always available event with PC turned off, but I like to use other modules on this stream deck. I'm using the image from https://user.bitfocus.io/product/companion-pi so not sure what OS is used.

**Comment by thedist** [comment]
Discord can only be connected to over IPC, meaning it has to be running on the same machine as Companion. There's no capability for Companion to be running on one machine/device, and Discord running on a completely separate device.

It is planned for a future release to be able to download and run a proxy service on the same machine as Discord, and then Companion can connect over the network to that proxy, but that is not yet ready. So for your situation where you're running Companion on a Raspberry Pi, unless you also install and use Discord on that same Raspberry Pi, this module isn't currently supported.
