### ISSUE TITLE
[Bug] Connection failure on new config

### ISSUE THREAD

**Issue by Rizotochaud** [bitfocus/companion-module-discord-api#11]
**Describe the bug**
After the configuration of the instance and connection to Discord with the login prompt, the instance displays Connection Failure

**To Reproduce**
Steps to reproduce the behaviour:

1. From a fresh install, create a discord instance
2. Enter credentials
3. Save and enable
4. Accept connection in the Discord app
5. Connection Failure

I made a new app on Discord Dev Portal to get new credentials as the console says "Login err" but it is not the solution

**System (please complete the following information):**

- Companion ver. 3.0.0 (3.0.0+6014-beta-c62d68b4)
- Discord module v 1.1.2

**Console log**
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\discord-api\main.js" **
system: ** Connection started **
Starting up module class: c
Sentry disabled
Module-host accepted registration
debug: Initializing Discord client
warn: Login err: {}
error: [object Object]`

**Comment by thedist** [comment]
Is the user account that created the Discord app the same user account that's logged in to Discord?

**Comment by RizoWBD** [comment]
Yes, same account.

**Comment by thedist** [comment]
The module works perfectly fine when ran directly as a dev module, but Companions packaging process seems to be breaking the module when packaged so I'm looking in to why that's happening.

**Comment by thedist** [comment]
This should be fixed in the latest beta builds.
