### ISSUE TITLE
Connection config unavailable

### ISSUE THREAD

**Issue by travmason** [bitfocus/companion-module-discord-api#16]
**Describe the bug**
Just trying to install and configure here but I can't find any reference to how to do that. I've got an App setup in Discord for this ready to go with keys but where do I configure the module? Right now I'm getting a "Connection config unavailable" message with a retry set to 1sec just looping away.

**To Reproduce**
Add the module. No configuration available. goes straight into the "Connection config unavailable" loop.

**Expected behaviour**
Provide an interface to add the Discord application keys?

**Screenshots**
![image](https://github.com/bitfocus/companion-module-discord-api/assets/1578379/c4209777-a6b4-4458-8dc8-bc5f291497b3)

**System (please complete the following information):**

- Companion Version [3.0.0 (3.0.0+5804-beta-71c001d4)](https://bitfocus.io/companion/)

**Additional context**
Need some more into the Readme.md. I'm happy to write some word for people if you can point me at what that should be.

**Comment by thedist** [comment]
Can you please try a more recent version of Companion and see if you still have the issue.

Also, what more info do you need in the readme? The config page itself has step by step instructions.

**Comment by travmason** [comment]
Which page? I can't find any other documentation??

**Comment by thedist** [comment]
![discord config](https://github.com/bitfocus/companion-module-discord-api/assets/12213790/4a61adfb-fc2b-49ae-a5c6-05b10c9585dc)

**Comment by travmason** [comment]
> ![discord config](https://github.com/bitfocus/companion-module-discord-api/assets/12213790/4a61adfb-fc2b-49ae-a5c6-05b10c9585dc)
> 
> 

Yeah so this is why I raised as a bug. It doesn't get to this point before failure. I'll try the latest beta and see if that works.

**Comment by thedist** [comment]
Yeah, you're a couple hundred commits behind the current released version, and the beta even further still (there hasn't been any changes to the Discord module between stable and beta, so they both should work).

**Comment by travmason** [comment]
Works in [3.1.0 (3.1.0+6056-beta-1384fc37)].
