### ISSUE TITLE
Module fails to load

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-discord-api#4]
**Describe the bug**

It looks like the png64 folder is not being handled by typescript properly, resulting in the module being unimportable.

**To Reproduce**

```
julus@julus-thinkpad:~/Projects/companion-22$ node
Welcome to Node.js v14.19.2.
Type ".help" for more information.
> require('companion-module-discord-api')
Uncaught Error: Cannot find module './png64'
Require stack:
- /home/julus/Projects/companion-22/node_modules/companion-module-discord-api/dist/feedback.js
- /home/julus/Projects/companion-22/node_modules/companion-module-discord-api/dist/index.js
- <repl>
```

The same is also happening on my ubuntu-server installation of companion. 

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**

- Companion Version [e.g. 2.2.0 (70d5207-2717)]

**Additional context**

**Comment by thedist** [comment]
I've been trying to look in to it, but it builds perfectly fine for me so is a bit hard to debug. I may try just putting all the png64 stuff into a single file rather than a folder as that's all I can think of.

**Comment by Julusian** [comment]
Ooh interesting.. It works when doing it from module-local-dev, but not when a dependency of companion (inside of node_modules).. how strange

**Comment by Julusian** [comment]
It looks like in module-local-dev tsc is making sure all dependency files are compiled, even if they arent referenced in the tsconfig includes (src/png64/index.ts isnt covered by the include rule).
But when in node_modules it is only compiling those in the tsconfig include.

I cant explain why it is doing this, and a quick google is not coming up with anything..
I think the easiest solution here would be to inline those files.
Also to make the line be `"include": ["src/**/*.ts"],` in tsconfig.json so that it will definitely compile all ts files in subdirectories.

Another thing of note, is that you have `"typescript": "^4.5.5"` as your devDependency (yarn.lock says it is currently 4.6.2), but are doing `npx typescript@^4.2.3` in the `yarn build`, which for me is being done wih 4.7.4. I would recommend making them both be `~4.6` to lock it to a specific minor version number, as typescript frequently have breaking changing in minor releases. What compiles today under 4.7 may not work under 4.8, and `npx typescript@^4.2.3` will be using 4.8 once it is released.

**Comment by thedist** [comment]
This should now be fixed.
