### ISSUE TITLE
Module not connecting to discord

### ISSUE THREAD

**Issue by James-Brittain** [bitfocus/companion-module-discord-api#5]
**Describe the bug**
When adding the discord module and entering the Client ID/Secret the status stays on "conencting"
upon adding the module i do get the discord prompt to allow access to bifcous but approving this doesnt change the connecting state and bitfocus does not appear in the list of authorised apps.

Have included the logs below

**Screenshots**
![image](https://user-images.githubusercontent.com/60820453/206521406-34fbedaa-8d2d-4197-a3df-3e43ef865bc2.png)
![image](https://user-images.githubusercontent.com/60820453/206521727-058f675e-32ca-459e-a393-68e8d89fff9f.png)
![image](https://user-images.githubusercontent.com/60820453/206521750-bd878c85-5cb6-4c4b-afb8-ce6465adda77.png)

**System (please complete the following information):**
Win 11 - 21H2
Companion 2.4.1

**Comment by thedist** [comment]
Just to check, you're logged in to Discord as the same account that was used to create the app and get the credentials?

**Comment by James-Brittain** [comment]
Yep, just checked to be sure it is the same account

**Comment by James-Brittain** [comment]
unsure if its signficant but if i force close companion, when i reopen it always prompts for the discorcd external application prompt.

![image](https://user-images.githubusercontent.com/60820453/206664427-a7281fc3-47a9-4036-8b98-0536bc8902ad.png)

**Comment by James-Brittain** [comment]
tried adding this on a mac but had the same results, 

<img width="410" alt="image" src="https://user-images.githubusercontent.com/60820453/207406051-5f17c61b-361d-4581-b1f7-e03bf96cbe7c.png">

**Comment by thedist** [comment]
I'll Have another look at this while I'm working on updating the module for Companion v3, but right now I'm not sure what the issue you're experiencing is as none of our testers can reproduce it.

**Comment by navhaxs** [comment]
@James-Brittain do check that you are using the "Client Secret" from here:

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/5162718/208355060-1ee0773d-3470-4985-a367-1e11636bc9a4.png">

I had the same 'symptoms' as you... and only after I cloned the Companion source code could I better debug why I was stuck 😅

**Comment by James-Brittain** [comment]
Hi @navhaxs, yeah that was the secret i was using, i deleted everything and started from scratch and it seems to be working now - im not sure if i did anything different here or if there was an update?

Either way thank you and @thedist for looking into this!
